# Generated by Django 5.2 on 2025-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Инициализирован'), ('in_progress', 'В процессе'), ('finished', 'Окончен')], default='init', max_length=25),
        ),
    ]
