# Generated by Django 5.2 on 2025-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_position_distance_position_speed_run_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
