# Generated by Django 5.2 on 2025-11-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
