# Generated by Django 5.2 on 2025-11-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_run_finish_time_run_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeComplete',
        ),
    ]
